---
# Set vm.swappiness to 1 in /etc/sysctl.conf
- name: add vm swappiness 
  sysctl:
    name: vm.swappiness
    value: "{{ swapness }}"
    state: present

# Set virtual max area /etc/sysctl.conf
- name: add vm max map count
  sysctl:
    name: vm.max_map_count
    value: "{{ vm_max_count }}"
    state: present
