---
- name: Set system limits for {{ elasticsearch_name }}
  community.general.pam_limits:
    domain: "{{ elasticsearch_name }}"
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.item }}"
    value: "{{ item.value }}"
  loop:
    - {
        type: "soft",
        item: "nofile",
        value: "{{ elasticsearch_nofile_limit }}",
      }
    - {
        type: "hard",
        item: "nofile",
        value: "{{ elasticsearch_nofile_limit }}",
      }
    - { type: "soft", item: "nproc", value: "{{ elasticsearch_nproc_limit }}" }
    - { type: "hard", item: "nproc", value: "{{ elasticsearch_nproc_limit }}" }
    - { type: "soft", item: "memlock", value: "unlimited" }
    - { type: "hard", item: "memlock", value: "unlimited" }

# Update environment for elasticsearch
- name: Configure {{ elasticsearch_name }} service and environment
  ansible.builtin.template:
    src: "{{ item.name }}"
    dest: "{{ item.path }}"
    mode: "0660"
  with_items:
    - {name: "limit.conf.j2", path: "/etc/security/limits.d/{{ elasticsearch_name }}.conf"}
    - {name: "elasticsearch.service.j2", path: "{{ elasticsearch_systemd_path }}/elasticsearch.service"}
  notify:
    - Reload systemd
    - Restart elasticsearch

# Update elasticsearch config files
- name: Create {{ elasticsearch_name }} configuration files
  ansible.builtin.template:
    src: "{{ item.name }}"
    dest: "{{ item.path }}"
    owner: "root"
    group: "{{ elasticsearch_name }}"
    mode: "0660"
  with_items:
    - { name: 'elasticsearch.yml.j2', path: '{{ elasticsearch_conf_path }}/elasticsearch.yml' }
    - { name: 'jvm.options.j2', path: '{{ elasticsearch_conf_path }}/jvm.options' }
  notify:
    - Restart elasticsearch

- name: Ensure correct ownership and permissions for configuration directory
  ansible.builtin.file:
    path: "{{ elasticsearch_conf_path }}"
    owner: "{{ elasticsearch_name }}"
    group: "{{ elasticsearch_name }}"
    mode: "0770"
    recurse: true
