---
- name: Add {{ elasticsearch_name }} GPG key
  ansible.builtin.apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

# Install apt-transports package required for installation of elasticsearch
- name: Install apt-transports
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
    update_cache: true

# Download elasticsearch
- name: Add {{ elasticsearch_name }} repository
  ansible.builtin.apt_repository:
    repo: >-
      deb https://artifacts.elastic.co/packages/{{
      elasticsearch_series }}.x/apt stable main
    state: present

- name: Install {{ elasticsearch_name }}
  ansible.builtin.apt:
    name: "elasticsearch={{ elasticsearch_version }}"
    state: present
    update_cache: true

# Create directory for data and heap_dump storage
- name: Create data and heap dump directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ elasticsearch_name }}"
    group: "{{ elasticsearch_name }}"
    mode: 0775
    recurse: true
  with_items:
    - "{{ elasticsearch_data_path }}"
    - "{{ elasticsearch_jvm_dump }}"
