---
# Set vm.swappiness to 1 in /etc/sysctl.conf
- sysctl:
    name: vm.swappiness
    value: "{{ swapness }}"
    state: present

# Set virtual max area /etc/sysctl.conf
- sysctl:
    name: vm.max_map_count
    value: "{{ vm_max_count }}"
    state: present

# Install apt-transports package required for Installation of Elasticsearch
- name: install apt-transports
  apt: name=apt-transport-https state=present update_cache=yes

# Download elasticsearch
- name: Add elasticsearch repository...
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}.x/apt stable main'
    state: present

- name: Update cache...
  apt:
    update_cache: yes
    cache_valid_time: 86400
  tags:
    - test

- name: Installing elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes


# enable openfile limit without restart
- name: enable open file witout restart
  shell: "ulimit -n 4096"


# Create directory for es_data and heap_dump storage
- name: Create data_path directory
  file:
    path: "{{ item }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0775
    recurse: yes
  with_items:
    - "{{ data_path }}"
    - "{{ es_jvm_dump }}"
  notify:
    - restart elasticsearch

- name: enable elasticsearch
  systemd:
    name: elasticsearch
    state: started
    enabled: yes
