---
- name: Add elasticsearch GPG key
  ansible.builtin.apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

# Install apt-transports package required for Installation of Elasticsearch
- name: install apt-transports
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
    update_cache: yes

# Download elasticsearch
- name: Add elasticsearch repository...
  ansible.builtin.apt_repository:
    repo: >-
      deb https://artifacts.elastic.co/packages/{{
      es_series }}.x/apt stable main
    state: present

- name: Update cache...
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Installing elasticsearch
  ansible.builtin.apt:
    name: "elasticsearch={{ elasticsearch_version }}"
    state: present
    update_cache: yes

# Create directory for es_data and heap_dump storage
- name: Create data_path directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0775
    recurse: yes
  with_items:
    - "{{ data_path }}"
    - "{{ es_jvm_dump }}"
