---
# Install libselinux-python on CentOS 7
- name: Install net-tools
  ansible.builtin.yum:
    name: net-tools
    state: present

- name: Download RPM package
  ansible.builtin.get_url:
    url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}-x86_64.rpm"
    dest: "/tmp/elasticsearch-{{ elasticsearch_version }}.rpm"
    mode: '0644'

# Install RPM file for elasticsearch
- name: Install {{ elasticsearch_name }}
  ansible.builtin.yum:
    name: "/tmp/elasticsearch-{{ elasticsearch_version }}.rpm"
    state: present
  notify:
    - Restart elasticsearch

# Create directory for data and heap_dump storage
- name: Create data and heap dump directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ elasticsearch_name }}"
    group: "{{ elasticsearch_name }}"
    mode: 0775
    recurse: true
  with_items:
    - "{{ elasticsearch_data_path }}"
    - "{{ elasticsearch_jvm_dump }}"
  notify:
    - Restart elasticsearch
