---
# install libselinux-python on centos7
- name: Install net-tools
  ansible.builtin.yum:
    name: net-tools
    state: present

- name: Download rpm.
  ansible.builtin.get_url:
    url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}-x86_64.rpm"
    dest: "/tmp/elasticsearch-{{ elasticsearch_version }}.rpm"
    mode: '0644'

# Install rpm file elasticsearch
- name: install elasticsearch
  ansible.builtin.yum:
    name: "/tmp/elasticsearch-{{ elasticsearch_version }}.rpm"
    state: present
  notify:
    - restart elasticsearch

# Create directory for es_data and heap_dump storage
- name: Create data_path directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0775
    recurse: yes
  with_items:
    - "{{ data_path }}"
    - "{{ es_jvm_dump }}"
  notify:
    - restart elasticsearch
