---
- name: Ensure Elasticsearch keystore exists
  ansible.builtin.command:
    cmd: "{{ elasticsearch_home }}/bin/elasticsearch-keystore create"
    creates: "{{ elasticsearch_conf_path }}/elasticsearch.keystore"

- name: Ensure Elasticsearch keystore has correct permissions
  ansible.builtin.file:
    path: "{{ elasticsearch_conf_path }}/elasticsearch.keystore"
    owner: "{{ elasticsearch_name }}"
    group: "{{ elasticsearch_name }}"
    mode: '0660'

- name: Check keystore entries
  ansible.builtin.command:
    cmd: "{{ elasticsearch_home }}/bin/elasticsearch-keystore list"
  register: keystore_list
  changed_when: false
  check_mode: false

- name: Purge stale OIDC settings from keystore (Required for Clean Boot)
  ansible.builtin.command:
    cmd: 'su -s /bin/bash {{ elasticsearch_name }} -c "{{ elasticsearch_home }}/bin/elasticsearch-keystore remove xpack.security.authc.realms.oidc.oidc_keycloak.rp.client_secret"'
  when: "'xpack.security.authc.realms.oidc.oidc_keycloak.rp.client_secret' in keystore_list.stdout"

- name: Check if custom user exists
  ansible.builtin.shell: "{{ elasticsearch_home }}/bin/elasticsearch-users list | grep -w {{ elasticsearch_user }}"
  register: user_check
  failed_when: false
  changed_when: false

- name: Create custom administrative user
  ansible.builtin.shell: "{{ elasticsearch_home }}/bin/elasticsearch-users useradd {{ elasticsearch_user }} -p {{ elasticsearch_password }} -r {{ elasticsearch_user_roles | join(',') }}"
  when: user_check.rc != 0
  no_log: true



- name: Final permission check for configuration directory
  ansible.builtin.file:
    path: "{{ elasticsearch_conf_path }}"
    owner: "{{ elasticsearch_name }}"
    group: "{{ elasticsearch_name }}"
    mode: "0770"
    recurse: true
