---
- name: Check if custom user exists
  ansible.builtin.shell: "{{ elasticsearch_home }}/bin/elasticsearch-users list | grep -w {{ elasticsearch_user }}"
  register: user_check
  failed_when: false
  changed_when: false

- name: Create custom administrative user
  ansible.builtin.shell: "{{ elasticsearch_home }}/bin/elasticsearch-users useradd {{ elasticsearch_user }} -p {{ elasticsearch_password }} -r {{ elasticsearch_user_roles | join(',') }}"
  when: user_check.rc != 0
  no_log: true
