---
- name: Add OIDC Client Secret to Elasticsearch Keystore
  ansible.builtin.shell: |
    su -s /bin/bash {{ elasticsearch_name }} -c "echo '{{ item.rp_client_secret }}' | {{ elasticsearch_home }}/bin/elasticsearch-keystore add -x -f 'xpack.security.authc.realms.oidc.{{ item.name }}.rp.client_secret'"
  loop: "{{ elasticsearch_oidc_realms }}"
  when: elasticsearch_oidc_enable | bool

- name: Ensure Elasticsearch keystore has correct permissions
  ansible.builtin.file:
    path: "{{ elasticsearch_conf_path }}/elasticsearch.keystore"
    owner: "{{ elasticsearch_name }}"
    group: "{{ elasticsearch_name }}"
    mode: '0660'
  when: elasticsearch_oidc_enable | bool

- name: Check if custom user exists
  ansible.builtin.shell: "{{ elasticsearch_home }}/bin/elasticsearch-users list | grep -w {{ elasticsearch_user }}"
  register: user_check
  failed_when: false
  changed_when: false

- name: Create custom administrative user
  ansible.builtin.shell: "{{ elasticsearch_home }}/bin/elasticsearch-users useradd {{ elasticsearch_user }} -p {{ elasticsearch_password }} -r {{ elasticsearch_user_roles | join(',') }}"
  when: user_check.rc != 0
  no_log: true
