---
# Tasks file for elasticsearch

- name: Configuring common configuration
  ansible.builtin.include_tasks: common.yml

- name: Include OS Specific setup tasks
  ansible.builtin.include_tasks: "es-{{ ansible_os_family }}.yml"

- name: Set system limits for elasticsearch
  community.general.pam_limits:
    domain: elasticsearch
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.item }}"
    value: "{{ item.value }}"
  with_items:
    - { type: 'soft', item: 'nofile', value: "{{ nofile_limit }}" }
    - { type: 'hard', item: 'nofile', value: "{{ nofile_limit }}" }
    - { type: 'soft', item: 'nproc', value: "{{ nproc_limit }}" }
    - { type: 'hard', item: 'nproc', value: "{{ nproc_limit }}" }
    - { type: 'soft', item: 'memlock', value: 'unlimited' }
    - { type: 'hard', item: 'memlock', value: 'unlimited' }

- ansible.builtin.include_tasks: config.yml

- name: manage tls certificates
  ansible.builtin.include_tasks: tls-encryption.yml
  when: tls_enable | bool

- name: Ensure elasticsearch is started
  ansible.builtin.service:
    name: elasticsearch
    state: started
    enabled: yes
    daemon_reload: yes

- name: Configure internal users
  ansible.builtin.include_tasks: users.yml
