---
# tasks file for logstash


- name: Fetch Java version
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: java_version

- assert:
    that: 
      - java_version is version('0.0.0', '>=') 
    fail_msg: "java is not present"

- name: Include OS Specific setup tasks
  include_tasks: es-{{ ansible_os_family }}.yml
  when: "'es' in group_names"

- include_tasks: config.yml
  when: "'es' in group_names"

- name: change config for master
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line: "node.master: true" 
  when: "'esm' in group_names"


- name: change config for data node
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line: "node.data: true"
  when: "'esd' in group_names"


- name: change config for client
  blockinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    block: |
      node.master: false
      node.data: false
  when: "'esc' in group_names"

