---
- name: Check if repository-s3 plugin is installed
  ansible.builtin.command:
    cmd: "{{ elasticsearch_home }}/bin/elasticsearch-plugin list"
  register: installed_plugins
  changed_when: false
  check_mode: false

- name: Install repository-s3 plugin
  ansible.builtin.command:
    cmd: "{{ elasticsearch_home }}/bin/elasticsearch-plugin install {{ elasticsearch_s3_plugin_name }} --batch"
  when: elasticsearch_s3_plugin_name not in installed_plugins.stdout
  notify: Restart elasticsearch
  register: plugin_install
  until: plugin_install is success
  retries: 3
  delay: 5
