---

# Create a temporary storage folder to download Java package
- name: Create Temporary Storage Folder
  file:
    path: "{{ java_tmp_storage }}"
    state: directory

# Donload Oracle Java RPM PACKAGE
- name: Download Oracle Java RPM
  get_url:
    url: "{{ __java_oracle_download }}"
    headers: 'Cookie:oraclelicense=accept-secure-backup-cookie'
    dest: "{{ java_tmp_storage }}/{{ __java_oracle_rpm }}.rpm"
#    checksum: "{{ __java_oracle_download_checksum }}"

# Install Oracle JAVA
- name: Install Oracle Java
  package:
    name: "{{ java_tmp_storage }}/{{ __java_oracle_rpm }}.rpm"
    state: installed
    validate_certs: False


- name: Add Elasticsearch GPG key.
  rpm_key:
    key: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository.
  copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: 0775

- name: Install Elasticsearch.
  yum: pkg=elasticsearch state=installed
  
- name: Starting Elasticsearch service
  service: name=elasticsearch state=started
