---
- name: Create certificate directory
  file:
    path: "/etc/elasticsearch/certs"
    state: directory
    owner: "elasticsearch"
    group: "elasticsearch"
    mode: 0775

# add certificates in nodes
- name: Add certificates in nodes
  copy:
    src: "{{ item.name }}"
    dest: "{{ item.path }}"
    mode: '0660'
  with_items:
    - {name: "{{ key }}", path: "{{ conf }}certs/{{ es_IP }}-node.key"}
    - {name: "{{ certificate }}", path: "{{ conf }}certs/{{ es_IP }}-node.crt"}
    - {name: "{{ certificate_auth }}", path: "{{ conf }}certs/ca.crt"}
  notify:
    - restart elasticsearch
