---

- name: Create certificate directory
  file:
    path: "/etc/elasticsearch/certs"
    state: directory
    owner: "elasticsearch"
    group: "elasticsearch"
    mode: 0775

# add certificates in nodes
- name: add certificates in nodes
  copy:
    src: "{{ item.name }}"
    dest: "{{ item.path }}"
  with_items:
    - {name: "{{ role_path }}/files/{{ key_name }}", path: "/etc/elasticsearch/certs/{{ es_IP }}-node.key"}
    - {name: "{{ role_path }}/files/{{ certificate_name }}", path: "/etc/elasticsearch/certs/{{ es_IP }}-node.crt"}
    - {name: "{{ role_path }}/files/{{ certificate_authorities_name }}", path: "/etc/elasticsearch/certs/ca.crt"}
  notify:
    - restart elasticsearch

