---

- name: Create certificate directory
  file:
    path: "/etc/elasticsearch/certs"
    state: directory
    owner: "elasticsearch"
    group: "elasticsearch"
    mode: 0775

# add certificates in nodes
- name: add certificates in nodes
  template:
    src: "{{ item.name }}"
    dest: "{{ item.path }}"
  with_items:
    - {name: "{{ cert_path }}", path: "/etc/elasticsearch/certs/elasticsearch.p12"}
  notify:
    - restart elasticsearch

