---
- name: Check if custom user exists
  ansible.builtin.shell: "{{ elasticsearch_home }}/bin/elasticsearch-users list | grep -w {{ elasticsearch_user }}"
  register: user_check
  failed_when: false
  changed_when: false
  run_once: true

- name: Create custom administrative user
  ansible.builtin.shell: "{{ elasticsearch_home }}/bin/elasticsearch-users useradd {{ elasticsearch_user }} -p {{ elasticsearch_password }} -r {{ elasticsearch_user_roles | join(',') }}"
  when: user_check.rc != 0
  run_once: true
  no_log: true

- name: Add OIDC Client Secret to Elasticsearch Keystore
  ansible.builtin.shell: |
    echo "{{ elasticsearch_oidc_rp_client_secret }}" | {{ elasticsearch_home }}/bin/elasticsearch-keystore add -x 'xpack.security.authc.realms.oidc.{{ elasticsearch_oidc_realm_name }}.rp.client_secret'
  when: elasticsearch_oidc_enable | bool
  register: keystore_oidc
  changed_when: keystore_oidc.rc == 0
  no_log: true
  notify: Restart elasticsearch

- name: Flush handlers to restart Elasticsearch with new keystore
  ansible.builtin.meta: flush_handlers

- name: Wait for Elasticsearch to be ready for API calls
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: "{{ elasticsearch_http_port }}"
    delay: 10
    timeout: 300

- name: Configure OIDC Role Mapping for Keycloak
  ansible.builtin.uri:
    url: "http://{{ ansible_host }}:{{ elasticsearch_http_port }}/_security/role_mapping/oidc_keycloak_mapping"
    method: POST
    user: "{{ elasticsearch_user }}"
    password: "{{ elasticsearch_password }}"
    force_basic_auth: true
    body_format: json
    body:
      enabled: true
      roles: ["superuser"]
      rules:
        all:
          - field: { realm.name: "{{ elasticsearch_oidc_realm_name }}" }
    status_code: [200, 201]
    validate_certs: false
  when: elasticsearch_oidc_enable | bool
