---
# handlers file for elasticsearch
- name: restart elasticsearch
  systemd:
    name: elasticsearch
    state: restarted
# reload systemd after modification
- name: reload systemd
  systemd:
    daemon_reload: yes
