---
# Handlers file for elasticsearch
- name: Restart elasticsearch
  ansible.builtin.systemd:
    name: "{{ elasticsearch_service }}"
    state: restarted

# Reload systemd after modification
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
