---
# Handlers file for elasticsearch
- name: Restart elasticsearch
  ansible.builtin.shell: |
    systemctl stop {{ elasticsearch_service }} || true
    pkill -9 -u {{ elasticsearch_name }} || true
    systemctl start {{ elasticsearch_service }}

# Reload systemd after modification
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: Restart kibana
  ansible.builtin.systemd:
    name: kibana
    state: restarted
